### ISSUE TITLE
U.S. map: single state

### ISSUE THREAD

**Issue by chasulin** [covid-projections/act-now-packages#57] opened 2022-08-11 18:20 UTC
closing in favor of [a duplicate ticket](https://github.com/orgs/covid-projections/projects/6/views/1)

**Comment by chasulin** [comment] 2022-08-11 18:22
- [ ] With county outline
- [ ] Without county outline

**Comment by smcclure17** [comment] 2022-09-12 14:42
close as duplicate of #165

**Closed as not planned** 2022-09-12 14:43 UTC
Labels: ui-components, packages
